# Site settings
title: "Tasnuba Sharmin"
description: "Tasnuba Sharmin Resume"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Tasnuba Sharmin"
resume_title:                   "Customer Services Manager"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "tasnuba.sharmin@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+880-17-30791889"
resume_contact_address:         "Dhaka, Bangladesh"

resume_header_contact_info:     "Dhaka, Bangladesh • +880-17-30791889 • tasnuba.sharmin@gmail.com"
display_header_contact_info:    "true"

resume_header_intro: "<p>I have over thirteen years of job experience, both in home and in the United Kingdom. My key activities are to provide outstanding customer services by leading and motivating team members, meet agreed sales targets and KPI lines, quality assurance and complaint management. I have expertise in recruiting staff, and training and developing sales team. I possess astute business knowledge and actively contribute to business through improvements of working processes, productivity and cost. I am a passionate trainer and deliver training across the British Council South Asia region. I am proficient in computerized bookkeeping with over three years of job experience.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "N/A"
  # resume_twitter_url:           "N/A"
  # resume_dribbble_url:          "N/A"
  resume_facebook_url:          "https://www.facebook.com/tasnubas"
  resume_linkedin_url:          "https://www.linkedin.com/in/tasnuba-s"
  # resume_instagram_url:         "N/A"
  # resume_website_url:           "N/A"
  # resume_medium_url:            "N/A"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
